# 网站基本信息
title: Code & Life
description: 记录技术学习与生活感悟
author: 你的名字

# 网站地址（修改成你的用户名）
url: "https://world2c.github.io"
baseurl: "/web_test"

# 使用的主题
theme: minima

# 语言设置
lang: zh-CN

# 显示文章摘要
show_excerpts: true

# 不再需要这个配置（可以删除）
# header_pages:
#   - tech.md
#   - life.md
#   - about.md
